AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge Rulestopec2
Resources:
  Ruleff7a65ad:
    Type: AWS::Events::Rule
    Properties:
      Name: stopec2
      ScheduleExpression: cron(0 14 * * ? *)
      State: ENABLED
      EventBusName: default
      Targets:
        - Id: Idf1239631-d495-4208-a852-87d414556bd0
          Arn:
            Fn::Sub: >-
              arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:startec2
Parameters: {}
